[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/",
    "permit2/=lib/v4-periphery/lib/permit2/",
    "solmate/=lib/v4-core/lib/solmate/",
]

[profile.default.fmt]
line_length = 120
tab_width = 4

[rpc_endpoints]
monad = "${MONAD_RPC_URL}"

[etherscan]
monad = { key = "${MONADSCAN_API_KEY}", url = "https://api.monadscan.com/api" }
